environment: "Development"
sqlConnectionString: "sqlserver://sa:@stefany@1994@localhost:1433?database=AccountControl"
cron: "30 10 * * *"
telegramBaseUrl: "https://api.telegram.org/bot"
botKey: ""
chatId: 0
