name: "Financial Control Events CI/CD"
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  golint:
    name: "Go Lint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  variable-substitution:
    name: "Variable Substitution"
    runs-on: ubuntu-20.04
    steps:
    - uses: microsoft/variable-substitution@v1 
      with:
        files: '*.yaml'
      env:
        sqlConnectionString: ${{ secrets.SQL_CONNECTION_STRING }}
        botKey: ${{ secrets.BOT_KEY }}
        chatId: ${{ secrets.CHAT_ID }}

  # deploy-heroku:
  #   name: "Deploy to Heroku"
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.11.10
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
  #         usedocker: true
  #         docker_heroku_process_type: worker
